# Generated by Django 4.0.3 on 2022-03-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geographical_description', models.TextField()),
                ('geographical_level', models.CharField(max_length=7)),
                ('ons_code', models.CharField(max_length=10)),
                ('measure_group_description', models.TextField()),
                ('disaggregation_level', models.TextField()),
                ('measure_value', models.FloatField()),
                ('imd_average_rank', models.FloatField(null=True)),
                ('annual_pay_mean', models.IntegerField(null=True)),
                ('population', models.IntegerField(null=True)),
                ('year', models.IntegerField(default=2021)),
            ],
        ),
    ]
